config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :conversations do
    post :private
  end

  get 'logs', to: 'home#logs'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_secure_password

  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  after_create_commit { MessageBroadcastWorker.perform_async(id, conversation.id, user.id) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :chatrooms, through: :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    render :index, locals: { conversations: Conversation.all }
  end

  def new
    render :new, locals: { conversation: Conversation.new }
  end

  def create
    conversation = Conversation.new(conversation_params)
    conversation.save(validate: false)

    respond_to do |format|
      format.html { redirect_to conversations_path, flash: {
        success: "Successful created #{conversation.topic}"
      } }
      format.js
    end
  end

  def private
    conversation = Conversation.find(params[:conversation_id])
    if conversation.authenticate(params[:password])
      render :show, locals: { conversation: conversation }
    else
      redirect_to conversations_path, flash: { error: "Invalid password, pes" }
    end
  end

  def show
    conversation = Conversation.find(params[:id])
    if conversation.password_digest && params[:password].blank?
      redirect_to conversations_path, flash: { error: "Private room, pes" }
    else
      render :show, locals: { conversation: conversation }
    end
  end

  private

  def conversation_params
    params.require(:conversation).permit(:topic, :password)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def logs
    render locals: { logs: %x{tail -20 log/custom_sidekiq.log}.split("\n") }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/conversations/_conversation.html.erb
<li>
  <div class="panel panel-default" data-conversation-id="<%= conversation.id %>">
    <div class="panel-body">
      <div class="messages-list">
        <ul>
          <%= render 'conversations/conversation_content', messages: conversation.messages, user: user %>
        </ul>
      </div>
      <form class="new_message">
        <input name="conversation_id" type="hidden" value="<%= conversation.id %>">
        <input name="user_id" type="hidden" value="<%= user.id %>">
        <textarea name="body" class="form-control" id='chat_area'></textarea>
        <input type="submit" class="btn btn-success" value="Send">
        <%= link_to 'Back to rooms', conversations_path, class: 'btn btn-warning' %>
      </form>
    </div>
  </div>
</li>

app/views/conversations/_conversation_content.html.erb
<% messages.each do |message| %>
  <%= render message, user: user %>
<% end %>

app/views/conversations/index.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1>Rooms:</h1>
    <div class="well">
      <ul>
        <% conversations.each do |room| %>
          <li>
            <h3>
              <% if room.password_digest %>
                <%= form_tag conversation_private_path(room) do %>
                  <%= text_field_tag :password, nil, placeholder: 'Password' %>
                  <%= submit_tag "Join #{room.topic} (private)" %>
                <% end %>
              <% else %>
                <%= link_to "Join #{room.topic}", room %>
              <% end %>
            </h3>
          </li>
        <% end %>
      </ul>
    </div>
</div>

app/views/conversations/new.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1>New room</h1>
    <div class="well">
      <div class="chatroom-form">
        <%= form_for conversation do |f| %>
          <div class="input-group">
            <span class="input-group-addon">Password (optional):</span>
            <%= f.text_field :password, class: "form-control" %>
          </div>
          <%= f.hidden_field :topic, value: "Room ##{Time.now.to_i}" %>
          <%= f.submit 'Create room', class: "btn btn-primary", id: "create-chatroom" %>
        <% end %>
      </div>
    </div>
</div>

app/views/conversations/show.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1><%= conversation.topic %></h1>
    <ul id="conversations-list" data-conversation="<%= conversation.id %>">
      <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
    </ul>
</div>

app/views/home/logs.html.erb
<% logs.each do |line| %>
  <%= line %>
  <br>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "PesChat", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render partial: 'layouts/navbar_links' %>
    </div>
  </div>
</nav>

app/views/layouts/_navbar_links.html.erb
<ul class="nav navbar-nav">
  <% if user_signed_in? %>
    <li><%= link_to "New Room", new_conversation_path %></li>
    <li><%= link_to "Rooms", conversations_path %></li>
    <li><%= link_to "Logs", logs_path %></li>
  <% end %>
</ul>

<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li><%= link_to current_user.email, '#' %></li>
    <li>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
    </li>
  <% else %>
    <li><%= link_to('Register', new_user_registration_path) %></li>
    <li><%= link_to('Login', new_user_session_path) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>
  <body>
    <%= render partial: 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<li>
  <div class="row">
    <div class='message-received'>
      <strong><%= message.user.email %>:</strong>
      <%= message.body %>
    </div>
  </div>
</li>

app/views/messages/_message_form.html.erb
<% if false %>
  <label for="message_your_message">Your message</label>:
    <textarea class="form-control" data-textarea="message" name="message[content]" id="message_content">
    </textarea>
  <input type="submit" name="commit" value="send" class="btn btn-primary" data-send="message" data-disable-with="send" />



  <form class="new_message">
    <input name="conversation_id" type="hidden" value="<%= conversation.id %>">
    <input name="user_id" type="hidden" value="<%= user.id %>">
    <textarea name="body" class="form-control"></textarea>
    <input type="submit" class="btn btn-success" value="Send">
  </form>

<% end %>